export default [
    {"value": "en-US" , "display": "US English"},
    {"value": "cmn-Hans-CN" , "display": "普通话 (中国大陆)"},
    {"value": "cmn-Hans-HK" , "display": "普通话 (香港)"},
    {"value": "cmn-Hant-TW" , "display": "中文 (台灣)"},
    {"value": "yue-Hant-HK", "display": "粵語 (香港)"},
    {"value": "ja-JP" , "display": "日本の"},
    {"value": "id-ID" , "display": "Bahasa, Indonesia"},
    {"value": "ms-MY" , "display": "Bahasa, Melayu"},
    {"value": "bg-BG" , "display": "Bulgarian"},
    {"value": "cs-CZ" , "display": "Czech"},
    {"value": "de-DE" , "display": "Deutsch"},
    {"value": "nl-NL" , "display": "Dutch, Netherlands"},
    {"value": "en-AU" , "display": "English, Australia"},
    {"value": "en-CA" , "display": "English, Canada"},
    {"value": "en-IN" , "display": "English, India"},
    {"value": "en-NZ" , "display": "English, New Zealand"},
    {"value": "en-ZA" , "display": "English, S. Africa"},
    {"value": "en-GB" , "display": "English, UK"},
    {"value": "en-US" , "display": "English, US"},
    {"value": "es-AR" , "display": "español, Argentina"},
    {"value": "es-BO" , "display": "español, Bolivia"},
    {"value": "es-CL" , "display": "español, Chile"},
    {"value": "es-CO" , "display": "español, Colombia"},
    {"value": "es-CR" , "display": "español, Costa Rica"},
    {"value": "es-EC" , "display": "español, Ecuador"},
    {"value": "es-SV" , "display": "español, El Salvador"},
    {"value": "es-ES" , "display": "español, España"},
    {"value": "es-US" , "display": "español, Estados Unidos"},
    {"value": "es-GT" , "display": "español, Guatemala"},
    {"value": "es-HN" , "display": "español, Honduras"},
    {"value": "es-MX" , "display": "español, México"},
    {"value": "es-NI" , "display": "español, Nicaragua"},
    {"value": "es-PA" , "display": "español, Panamá"},
    {"value": "es-PY" , "display": "español, Paraguay"},
    {"value": "es-PE" , "display": "español, Perú"},
    {"value": "es-PR" , "display": "español, Puerto Rico"},
    {"value": "es-DO" , "display": "español, R. Dominicana"},
    {"value": "es-UY" , "display": "español, Uruguay"},
    {"value": "es-VE" , "display": "español, Venezuela"},
    {"value": "fr-FR" , "display": "français"},
    {"value": "is-IS" , "display": "Icelandic"},
    {"value": "zu-ZA" , "display": "IsiZulu"},
    {"value": "it-IT" , "display": "italiano"},
    {"value": "it-CH" , "display": "italiano, Svizzera"},
    {"value": "ko-KR" , "display": "Korean"},
    {"value": "hu-HU" , "display": "Magyar"},
    {"value": "nb-NO" , "display": "Norwegian"},
    {"value": "pl-PL" , "display": "Polski"},
    {"value": "pt-BR" , "display": "Português, Brasil"},
    {"value": "pt-PT" , "display": "Português, Portugal"},
    {"value": "ro-RO" , "display": "română"},
    {"value": "ru-RU" , "display": "России"},
    {"value": "sr-RS" , "display": "Serbian"},
    {"value": "sk-SK" , "display": "Slovak"},
    {"value": "fi-FI" , "display": "Suomi"},
    {"value": "sv-SE" , "display": "Svenska"},
    {"value": "tr-TR" , "display": "Turkish"},
    {"value": "el-GR" , "display": "Ελληνικά"},
    {"value": "he-IL" , "display": "עברית"},
    {"value": "ar-DZ" , "display": "العربية, Algeria"},
    {"value": "ar-EG" , "display": "العربية, Egypt"},
    {"value": "ar-IQ" , "display": "العربية, Iraq"},
    {"value": "ar-JO" , "display": "العربية, Jordan"},
    {"value": "ar-KW" , "display": "العربية, Kuwait"},
    {"value": "ar-LB" , "display": "العربية, Lebanon"},
    {"value": "ar-MA" , "display": "العربية, Morocco"},
    {"value": "ar-QA" , "display": "العربية, Qatar"},
    {"value": "ar-SA" , "display": "العربية, Saudi Arabia"},
    {"value": "ar-AE" , "display": "العربية, UAE"},
]